// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2/v1/Feedback.proto

package com.al.cc.java.p2;

public final class FeedBackSchema {
  private FeedBackSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code p2_v1.ParkingLotType}
   */
  public enum ParkingLotType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDERGROUND = 0;</code>
     */
    UNDERGROUND(0),
    /**
     * <code>OUTSIDE = 1;</code>
     */
    OUTSIDE(1),
    ;

    /**
     * <code>UNDERGROUND = 0;</code>
     */
    public static final int UNDERGROUND_VALUE = 0;
    /**
     * <code>OUTSIDE = 1;</code>
     */
    public static final int OUTSIDE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ParkingLotType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ParkingLotType forNumber(int value) {
      switch (value) {
        case 0: return UNDERGROUND;
        case 1: return OUTSIDE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ParkingLotType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ParkingLotType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ParkingLotType>() {
            public ParkingLotType findValueByNumber(int number) {
              return ParkingLotType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.al.cc.java.p2.FeedBackSchema.getDescriptor().getEnumTypes().get(0);
    }

    private static final ParkingLotType[] VALUES = values();

    public static ParkingLotType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ParkingLotType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:p2_v1.ParkingLotType)
  }

  /**
   * Protobuf enum {@code p2_v1.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FEMALE = 0;</code>
     */
    FEMALE(0),
    /**
     * <code>MALE = 1;</code>
     */
    MALE(1),
    ;

    /**
     * <code>FEMALE = 0;</code>
     */
    public static final int FEMALE_VALUE = 0;
    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return FEMALE;
        case 1: return MALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.al.cc.java.p2.FeedBackSchema.getDescriptor().getEnumTypes().get(1);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:p2_v1.Gender)
  }

  public interface FeedbackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:p2_v1.Feedback)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
     * @return Whether the lifeCycleId field is set.
     */
    boolean hasLifeCycleId();
    /**
     * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
     * @return The lifeCycleId.
     */
    long getLifeCycleId();

    /**
     * <code>optional string name = 2 [default = "-9999"];</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = "-9999"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2 [default = "-9999"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string gc_id = 3 [default = "-9999"];</code>
     * @return Whether the gcId field is set.
     */
    boolean hasGcId();
    /**
     * <code>optional string gc_id = 3 [default = "-9999"];</code>
     * @return The gcId.
     */
    java.lang.String getGcId();
    /**
     * <code>optional string gc_id = 3 [default = "-9999"];</code>
     * @return The bytes for gcId.
     */
    com.google.protobuf.ByteString
        getGcIdBytes();

    /**
     * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
     * @return Whether the gender field is set.
     */
    boolean hasGender();
    /**
     * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
     * @return The gender.
     */
    com.al.cc.java.p2.FeedBackSchema.Gender getGender();

    /**
     * <code>optional string id = 5 [default = "-9999"];</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional string id = 5 [default = "-9999"];</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 5 [default = "-9999"];</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
     * @return Whether the parkingLotType field is set.
     */
    boolean hasParkingLotType();
    /**
     * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
     * @return The parkingLotType.
     */
    com.al.cc.java.p2.FeedBackSchema.ParkingLotType getParkingLotType();

    /**
     * <code>optional bool ePay = 7 [default = true];</code>
     * @return Whether the ePay field is set.
     */
    boolean hasEPay();
    /**
     * <code>optional bool ePay = 7 [default = true];</code>
     * @return The ePay.
     */
    boolean getEPay();
  }
  /**
   * Protobuf type {@code p2_v1.Feedback}
   */
  public static final class Feedback extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:p2_v1.Feedback)
      FeedbackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Feedback.newBuilder() to construct.
    private Feedback(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Feedback() {
      lifeCycleId_ = -9999L;
      name_ = "-9999";
      gcId_ = "-9999";
      gender_ = 1;
      id_ = "-9999";
      parkingLotType_ = 1;
      ePay_ = true;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Feedback();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Feedback(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              lifeCycleId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              gcId_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.al.cc.java.p2.FeedBackSchema.Gender value = com.al.cc.java.p2.FeedBackSchema.Gender.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                gender_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              id_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.al.cc.java.p2.FeedBackSchema.ParkingLotType value = com.al.cc.java.p2.FeedBackSchema.ParkingLotType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                parkingLotType_ = rawValue;
              }
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              ePay_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.al.cc.java.p2.FeedBackSchema.internal_static_p2_v1_Feedback_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.al.cc.java.p2.FeedBackSchema.internal_static_p2_v1_Feedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.al.cc.java.p2.FeedBackSchema.Feedback.class, com.al.cc.java.p2.FeedBackSchema.Feedback.Builder.class);
    }

    private int bitField0_;
    public static final int LIFE_CYCLE_ID_FIELD_NUMBER = 1;
    private long lifeCycleId_;
    /**
     * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
     * @return Whether the lifeCycleId field is set.
     */
    @java.lang.Override
    public boolean hasLifeCycleId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
     * @return The lifeCycleId.
     */
    @java.lang.Override
    public long getLifeCycleId() {
      return lifeCycleId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2 [default = "-9999"];</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2 [default = "-9999"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = "-9999"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GC_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object gcId_;
    /**
     * <code>optional string gc_id = 3 [default = "-9999"];</code>
     * @return Whether the gcId field is set.
     */
    @java.lang.Override
    public boolean hasGcId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string gc_id = 3 [default = "-9999"];</code>
     * @return The gcId.
     */
    @java.lang.Override
    public java.lang.String getGcId() {
      java.lang.Object ref = gcId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gcId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gc_id = 3 [default = "-9999"];</code>
     * @return The bytes for gcId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGcIdBytes() {
      java.lang.Object ref = gcId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
     * @return Whether the gender field is set.
     */
    @java.lang.Override public boolean hasGender() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
     * @return The gender.
     */
    @java.lang.Override public com.al.cc.java.p2.FeedBackSchema.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.al.cc.java.p2.FeedBackSchema.Gender result = com.al.cc.java.p2.FeedBackSchema.Gender.valueOf(gender_);
      return result == null ? com.al.cc.java.p2.FeedBackSchema.Gender.MALE : result;
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 5 [default = "-9999"];</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string id = 5 [default = "-9999"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 5 [default = "-9999"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARKINGLOTTYPE_FIELD_NUMBER = 6;
    private int parkingLotType_;
    /**
     * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
     * @return Whether the parkingLotType field is set.
     */
    @java.lang.Override public boolean hasParkingLotType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
     * @return The parkingLotType.
     */
    @java.lang.Override public com.al.cc.java.p2.FeedBackSchema.ParkingLotType getParkingLotType() {
      @SuppressWarnings("deprecation")
      com.al.cc.java.p2.FeedBackSchema.ParkingLotType result = com.al.cc.java.p2.FeedBackSchema.ParkingLotType.valueOf(parkingLotType_);
      return result == null ? com.al.cc.java.p2.FeedBackSchema.ParkingLotType.OUTSIDE : result;
    }

    public static final int EPAY_FIELD_NUMBER = 7;
    private boolean ePay_;
    /**
     * <code>optional bool ePay = 7 [default = true];</code>
     * @return Whether the ePay field is set.
     */
    @java.lang.Override
    public boolean hasEPay() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bool ePay = 7 [default = true];</code>
     * @return The ePay.
     */
    @java.lang.Override
    public boolean getEPay() {
      return ePay_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, lifeCycleId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gcId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, gender_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, parkingLotType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBool(7, ePay_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lifeCycleId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gcId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, gender_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, parkingLotType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, ePay_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.al.cc.java.p2.FeedBackSchema.Feedback)) {
        return super.equals(obj);
      }
      com.al.cc.java.p2.FeedBackSchema.Feedback other = (com.al.cc.java.p2.FeedBackSchema.Feedback) obj;

      if (hasLifeCycleId() != other.hasLifeCycleId()) return false;
      if (hasLifeCycleId()) {
        if (getLifeCycleId()
            != other.getLifeCycleId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasGcId() != other.hasGcId()) return false;
      if (hasGcId()) {
        if (!getGcId()
            .equals(other.getGcId())) return false;
      }
      if (hasGender() != other.hasGender()) return false;
      if (hasGender()) {
        if (gender_ != other.gender_) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasParkingLotType() != other.hasParkingLotType()) return false;
      if (hasParkingLotType()) {
        if (parkingLotType_ != other.parkingLotType_) return false;
      }
      if (hasEPay() != other.hasEPay()) return false;
      if (hasEPay()) {
        if (getEPay()
            != other.getEPay()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLifeCycleId()) {
        hash = (37 * hash) + LIFE_CYCLE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLifeCycleId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasGcId()) {
        hash = (37 * hash) + GC_ID_FIELD_NUMBER;
        hash = (53 * hash) + getGcId().hashCode();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + gender_;
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasParkingLotType()) {
        hash = (37 * hash) + PARKINGLOTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + parkingLotType_;
      }
      if (hasEPay()) {
        hash = (37 * hash) + EPAY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getEPay());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.al.cc.java.p2.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.al.cc.java.p2.FeedBackSchema.Feedback prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code p2_v1.Feedback}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:p2_v1.Feedback)
        com.al.cc.java.p2.FeedBackSchema.FeedbackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.al.cc.java.p2.FeedBackSchema.internal_static_p2_v1_Feedback_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.al.cc.java.p2.FeedBackSchema.internal_static_p2_v1_Feedback_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.al.cc.java.p2.FeedBackSchema.Feedback.class, com.al.cc.java.p2.FeedBackSchema.Feedback.Builder.class);
      }

      // Construct using com.al.cc.java.p2.FeedBackSchema.Feedback.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lifeCycleId_ = -9999L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "-9999";
        bitField0_ = (bitField0_ & ~0x00000002);
        gcId_ = "-9999";
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = 1;
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = "-9999";
        bitField0_ = (bitField0_ & ~0x00000010);
        parkingLotType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000020);
        ePay_ = true;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.al.cc.java.p2.FeedBackSchema.internal_static_p2_v1_Feedback_descriptor;
      }

      @java.lang.Override
      public com.al.cc.java.p2.FeedBackSchema.Feedback getDefaultInstanceForType() {
        return com.al.cc.java.p2.FeedBackSchema.Feedback.getDefaultInstance();
      }

      @java.lang.Override
      public com.al.cc.java.p2.FeedBackSchema.Feedback build() {
        com.al.cc.java.p2.FeedBackSchema.Feedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.al.cc.java.p2.FeedBackSchema.Feedback buildPartial() {
        com.al.cc.java.p2.FeedBackSchema.Feedback result = new com.al.cc.java.p2.FeedBackSchema.Feedback(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lifeCycleId_ = lifeCycleId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gcId_ = gcId_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.parkingLotType_ = parkingLotType_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ePay_ = ePay_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.al.cc.java.p2.FeedBackSchema.Feedback) {
          return mergeFrom((com.al.cc.java.p2.FeedBackSchema.Feedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.al.cc.java.p2.FeedBackSchema.Feedback other) {
        if (other == com.al.cc.java.p2.FeedBackSchema.Feedback.getDefaultInstance()) return this;
        if (other.hasLifeCycleId()) {
          setLifeCycleId(other.getLifeCycleId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasGcId()) {
          bitField0_ |= 0x00000004;
          gcId_ = other.gcId_;
          onChanged();
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000010;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasParkingLotType()) {
          setParkingLotType(other.getParkingLotType());
        }
        if (other.hasEPay()) {
          setEPay(other.getEPay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.al.cc.java.p2.FeedBackSchema.Feedback parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.al.cc.java.p2.FeedBackSchema.Feedback) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long lifeCycleId_ = -9999L;
      /**
       * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
       * @return Whether the lifeCycleId field is set.
       */
      @java.lang.Override
      public boolean hasLifeCycleId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
       * @return The lifeCycleId.
       */
      @java.lang.Override
      public long getLifeCycleId() {
        return lifeCycleId_;
      }
      /**
       * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
       * @param value The lifeCycleId to set.
       * @return This builder for chaining.
       */
      public Builder setLifeCycleId(long value) {
        bitField0_ |= 0x00000001;
        lifeCycleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 life_cycle_id = 1 [default = -9999];</code>
       * @return This builder for chaining.
       */
      public Builder clearLifeCycleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lifeCycleId_ = -9999L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "-9999";
      /**
       * <code>optional string name = 2 [default = "-9999"];</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string name = 2 [default = "-9999"];</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "-9999"];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "-9999"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "-9999"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "-9999"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gcId_ = "-9999";
      /**
       * <code>optional string gc_id = 3 [default = "-9999"];</code>
       * @return Whether the gcId field is set.
       */
      public boolean hasGcId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string gc_id = 3 [default = "-9999"];</code>
       * @return The gcId.
       */
      public java.lang.String getGcId() {
        java.lang.Object ref = gcId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gcId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gc_id = 3 [default = "-9999"];</code>
       * @return The bytes for gcId.
       */
      public com.google.protobuf.ByteString
          getGcIdBytes() {
        java.lang.Object ref = gcId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gcId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gc_id = 3 [default = "-9999"];</code>
       * @param value The gcId to set.
       * @return This builder for chaining.
       */
      public Builder setGcId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        gcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gc_id = 3 [default = "-9999"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGcId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gcId_ = getDefaultInstance().getGcId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gc_id = 3 [default = "-9999"];</code>
       * @param value The bytes for gcId to set.
       * @return This builder for chaining.
       */
      public Builder setGcIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        gcId_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 1;
      /**
       * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
       * @return Whether the gender field is set.
       */
      @java.lang.Override public boolean hasGender() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
       * @return The gender.
       */
      @java.lang.Override
      public com.al.cc.java.p2.FeedBackSchema.Gender getGender() {
        @SuppressWarnings("deprecation")
        com.al.cc.java.p2.FeedBackSchema.Gender result = com.al.cc.java.p2.FeedBackSchema.Gender.valueOf(gender_);
        return result == null ? com.al.cc.java.p2.FeedBackSchema.Gender.MALE : result;
      }
      /**
       * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(com.al.cc.java.p2.FeedBackSchema.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .p2_v1.Gender gender = 4 [default = MALE];</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gender_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "-9999";
      /**
       * <code>optional string id = 5 [default = "-9999"];</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string id = 5 [default = "-9999"];</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 5 [default = "-9999"];</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 5 [default = "-9999"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 5 [default = "-9999"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 5 [default = "-9999"];</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }

      private int parkingLotType_ = 1;
      /**
       * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
       * @return Whether the parkingLotType field is set.
       */
      @java.lang.Override public boolean hasParkingLotType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
       * @return The parkingLotType.
       */
      @java.lang.Override
      public com.al.cc.java.p2.FeedBackSchema.ParkingLotType getParkingLotType() {
        @SuppressWarnings("deprecation")
        com.al.cc.java.p2.FeedBackSchema.ParkingLotType result = com.al.cc.java.p2.FeedBackSchema.ParkingLotType.valueOf(parkingLotType_);
        return result == null ? com.al.cc.java.p2.FeedBackSchema.ParkingLotType.OUTSIDE : result;
      }
      /**
       * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
       * @param value The parkingLotType to set.
       * @return This builder for chaining.
       */
      public Builder setParkingLotType(com.al.cc.java.p2.FeedBackSchema.ParkingLotType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        parkingLotType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .p2_v1.ParkingLotType parkingLotType = 6 [default = OUTSIDE];</code>
       * @return This builder for chaining.
       */
      public Builder clearParkingLotType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        parkingLotType_ = 1;
        onChanged();
        return this;
      }

      private boolean ePay_ = true;
      /**
       * <code>optional bool ePay = 7 [default = true];</code>
       * @return Whether the ePay field is set.
       */
      @java.lang.Override
      public boolean hasEPay() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional bool ePay = 7 [default = true];</code>
       * @return The ePay.
       */
      @java.lang.Override
      public boolean getEPay() {
        return ePay_;
      }
      /**
       * <code>optional bool ePay = 7 [default = true];</code>
       * @param value The ePay to set.
       * @return This builder for chaining.
       */
      public Builder setEPay(boolean value) {
        bitField0_ |= 0x00000040;
        ePay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ePay = 7 [default = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearEPay() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ePay_ = true;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:p2_v1.Feedback)
    }

    // @@protoc_insertion_point(class_scope:p2_v1.Feedback)
    private static final com.al.cc.java.p2.FeedBackSchema.Feedback DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.al.cc.java.p2.FeedBackSchema.Feedback();
    }

    public static com.al.cc.java.p2.FeedBackSchema.Feedback getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Feedback>
        PARSER = new com.google.protobuf.AbstractParser<Feedback>() {
      @java.lang.Override
      public Feedback parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feedback(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Feedback> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Feedback> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.al.cc.java.p2.FeedBackSchema.Feedback getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p2_v1_Feedback_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p2_v1_Feedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024p2/v1/Feedback.proto\022\005p2_v1\"\327\001\n\010Feedba" +
      "ck\022\034\n\rlife_cycle_id\030\001 \001(\003:\005-9999\022\023\n\004name" +
      "\030\002 \001(\t:\005-9999\022\024\n\005gc_id\030\003 \001(\t:\005-9999\022#\n\006g" +
      "ender\030\004 \001(\0162\r.p2_v1.Gender:\004MALE\022\021\n\002id\030\005" +
      " \001(\t:\005-9999\0226\n\016parkingLotType\030\006 \001(\0162\025.p2" +
      "_v1.ParkingLotType:\007OUTSIDE\022\022\n\004ePay\030\007 \001(" +
      "\010:\004true*.\n\016ParkingLotType\022\017\n\013UNDERGROUND" +
      "\020\000\022\013\n\007OUTSIDE\020\001*\036\n\006Gender\022\n\n\006FEMALE\020\000\022\010\n" +
      "\004MALE\020\001B#\n\021com.al.cc.java.p2B\016FeedBackSc" +
      "hema"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_p2_v1_Feedback_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p2_v1_Feedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p2_v1_Feedback_descriptor,
        new java.lang.String[] { "LifeCycleId", "Name", "GcId", "Gender", "Id", "ParkingLotType", "EPay", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
