// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p3/v1/Feedback.proto

package com.al.cc.java.p3;

public final class FeedBackSchema {
  private FeedBackSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code p3_v1.ParkingLotType}
   */
  public enum ParkingLotType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDERGROUND = 0;</code>
     */
    UNDERGROUND(0),
    /**
     * <code>OUTSIDE = 1;</code>
     */
    OUTSIDE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNDERGROUND = 0;</code>
     */
    public static final int UNDERGROUND_VALUE = 0;
    /**
     * <code>OUTSIDE = 1;</code>
     */
    public static final int OUTSIDE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ParkingLotType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ParkingLotType forNumber(int value) {
      switch (value) {
        case 0: return UNDERGROUND;
        case 1: return OUTSIDE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ParkingLotType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ParkingLotType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ParkingLotType>() {
            public ParkingLotType findValueByNumber(int number) {
              return ParkingLotType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.al.cc.java.p3.FeedBackSchema.getDescriptor().getEnumTypes().get(0);
    }

    private static final ParkingLotType[] VALUES = values();

    public static ParkingLotType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ParkingLotType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:p3_v1.ParkingLotType)
  }

  /**
   * Protobuf enum {@code p3_v1.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FEMALE = 0;</code>
     */
    FEMALE(0),
    /**
     * <code>MALE = 1;</code>
     */
    MALE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FEMALE = 0;</code>
     */
    public static final int FEMALE_VALUE = 0;
    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return FEMALE;
        case 1: return MALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.al.cc.java.p3.FeedBackSchema.getDescriptor().getEnumTypes().get(1);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:p3_v1.Gender)
  }

  public interface FeedbackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:p3_v1.Feedback)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 life_cycle_id = 1;</code>
     * @return The lifeCycleId.
     */
    long getLifeCycleId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string gc_id = 3;</code>
     * @return The gcId.
     */
    java.lang.String getGcId();
    /**
     * <code>string gc_id = 3;</code>
     * @return The bytes for gcId.
     */
    com.google.protobuf.ByteString
        getGcIdBytes();

    /**
     * <code>.p3_v1.Gender gender = 4;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <code>.p3_v1.Gender gender = 4;</code>
     * @return The gender.
     */
    com.al.cc.java.p3.FeedBackSchema.Gender getGender();

    /**
     * <code>string id = 5;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 5;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
     * @return The enum numeric value on the wire for parkingLotType.
     */
    int getParkingLotTypeValue();
    /**
     * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
     * @return The parkingLotType.
     */
    com.al.cc.java.p3.FeedBackSchema.ParkingLotType getParkingLotType();

    /**
     * <code>bool ePay = 7;</code>
     * @return The ePay.
     */
    boolean getEPay();

    /**
     * <code>int64 create_timestamp = 8;</code>
     * @return The createTimestamp.
     */
    long getCreateTimestamp();
  }
  /**
   * Protobuf type {@code p3_v1.Feedback}
   */
  public static final class Feedback extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:p3_v1.Feedback)
      FeedbackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Feedback.newBuilder() to construct.
    private Feedback(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Feedback() {
      name_ = "";
      gcId_ = "";
      gender_ = 0;
      id_ = "";
      parkingLotType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Feedback();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Feedback(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              lifeCycleId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              gcId_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              parkingLotType_ = rawValue;
              break;
            }
            case 56: {

              ePay_ = input.readBool();
              break;
            }
            case 64: {

              createTimestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.al.cc.java.p3.FeedBackSchema.internal_static_p3_v1_Feedback_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.al.cc.java.p3.FeedBackSchema.internal_static_p3_v1_Feedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.al.cc.java.p3.FeedBackSchema.Feedback.class, com.al.cc.java.p3.FeedBackSchema.Feedback.Builder.class);
    }

    public static final int LIFE_CYCLE_ID_FIELD_NUMBER = 1;
    private long lifeCycleId_;
    /**
     * <code>int64 life_cycle_id = 1;</code>
     * @return The lifeCycleId.
     */
    @java.lang.Override
    public long getLifeCycleId() {
      return lifeCycleId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GC_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object gcId_;
    /**
     * <code>string gc_id = 3;</code>
     * @return The gcId.
     */
    @java.lang.Override
    public java.lang.String getGcId() {
      java.lang.Object ref = gcId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gcId_ = s;
        return s;
      }
    }
    /**
     * <code>string gc_id = 3;</code>
     * @return The bytes for gcId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGcIdBytes() {
      java.lang.Object ref = gcId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <code>.p3_v1.Gender gender = 4;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.p3_v1.Gender gender = 4;</code>
     * @return The gender.
     */
    @java.lang.Override public com.al.cc.java.p3.FeedBackSchema.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.al.cc.java.p3.FeedBackSchema.Gender result = com.al.cc.java.p3.FeedBackSchema.Gender.valueOf(gender_);
      return result == null ? com.al.cc.java.p3.FeedBackSchema.Gender.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 5;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 5;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARKINGLOTTYPE_FIELD_NUMBER = 6;
    private int parkingLotType_;
    /**
     * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
     * @return The enum numeric value on the wire for parkingLotType.
     */
    @java.lang.Override public int getParkingLotTypeValue() {
      return parkingLotType_;
    }
    /**
     * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
     * @return The parkingLotType.
     */
    @java.lang.Override public com.al.cc.java.p3.FeedBackSchema.ParkingLotType getParkingLotType() {
      @SuppressWarnings("deprecation")
      com.al.cc.java.p3.FeedBackSchema.ParkingLotType result = com.al.cc.java.p3.FeedBackSchema.ParkingLotType.valueOf(parkingLotType_);
      return result == null ? com.al.cc.java.p3.FeedBackSchema.ParkingLotType.UNRECOGNIZED : result;
    }

    public static final int EPAY_FIELD_NUMBER = 7;
    private boolean ePay_;
    /**
     * <code>bool ePay = 7;</code>
     * @return The ePay.
     */
    @java.lang.Override
    public boolean getEPay() {
      return ePay_;
    }

    public static final int CREATE_TIMESTAMP_FIELD_NUMBER = 8;
    private long createTimestamp_;
    /**
     * <code>int64 create_timestamp = 8;</code>
     * @return The createTimestamp.
     */
    @java.lang.Override
    public long getCreateTimestamp() {
      return createTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lifeCycleId_ != 0L) {
        output.writeInt64(1, lifeCycleId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getGcIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gcId_);
      }
      if (gender_ != com.al.cc.java.p3.FeedBackSchema.Gender.FEMALE.getNumber()) {
        output.writeEnum(4, gender_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      if (parkingLotType_ != com.al.cc.java.p3.FeedBackSchema.ParkingLotType.UNDERGROUND.getNumber()) {
        output.writeEnum(6, parkingLotType_);
      }
      if (ePay_ != false) {
        output.writeBool(7, ePay_);
      }
      if (createTimestamp_ != 0L) {
        output.writeInt64(8, createTimestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lifeCycleId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lifeCycleId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getGcIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gcId_);
      }
      if (gender_ != com.al.cc.java.p3.FeedBackSchema.Gender.FEMALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, gender_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      if (parkingLotType_ != com.al.cc.java.p3.FeedBackSchema.ParkingLotType.UNDERGROUND.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, parkingLotType_);
      }
      if (ePay_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, ePay_);
      }
      if (createTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, createTimestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.al.cc.java.p3.FeedBackSchema.Feedback)) {
        return super.equals(obj);
      }
      com.al.cc.java.p3.FeedBackSchema.Feedback other = (com.al.cc.java.p3.FeedBackSchema.Feedback) obj;

      if (getLifeCycleId()
          != other.getLifeCycleId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getGcId()
          .equals(other.getGcId())) return false;
      if (gender_ != other.gender_) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (parkingLotType_ != other.parkingLotType_) return false;
      if (getEPay()
          != other.getEPay()) return false;
      if (getCreateTimestamp()
          != other.getCreateTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIFE_CYCLE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLifeCycleId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGcId().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + PARKINGLOTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + parkingLotType_;
      hash = (37 * hash) + EPAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEPay());
      hash = (37 * hash) + CREATE_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.al.cc.java.p3.FeedBackSchema.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.al.cc.java.p3.FeedBackSchema.Feedback prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code p3_v1.Feedback}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:p3_v1.Feedback)
        com.al.cc.java.p3.FeedBackSchema.FeedbackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.al.cc.java.p3.FeedBackSchema.internal_static_p3_v1_Feedback_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.al.cc.java.p3.FeedBackSchema.internal_static_p3_v1_Feedback_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.al.cc.java.p3.FeedBackSchema.Feedback.class, com.al.cc.java.p3.FeedBackSchema.Feedback.Builder.class);
      }

      // Construct using com.al.cc.java.p3.FeedBackSchema.Feedback.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lifeCycleId_ = 0L;

        name_ = "";

        gcId_ = "";

        gender_ = 0;

        id_ = "";

        parkingLotType_ = 0;

        ePay_ = false;

        createTimestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.al.cc.java.p3.FeedBackSchema.internal_static_p3_v1_Feedback_descriptor;
      }

      @java.lang.Override
      public com.al.cc.java.p3.FeedBackSchema.Feedback getDefaultInstanceForType() {
        return com.al.cc.java.p3.FeedBackSchema.Feedback.getDefaultInstance();
      }

      @java.lang.Override
      public com.al.cc.java.p3.FeedBackSchema.Feedback build() {
        com.al.cc.java.p3.FeedBackSchema.Feedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.al.cc.java.p3.FeedBackSchema.Feedback buildPartial() {
        com.al.cc.java.p3.FeedBackSchema.Feedback result = new com.al.cc.java.p3.FeedBackSchema.Feedback(this);
        result.lifeCycleId_ = lifeCycleId_;
        result.name_ = name_;
        result.gcId_ = gcId_;
        result.gender_ = gender_;
        result.id_ = id_;
        result.parkingLotType_ = parkingLotType_;
        result.ePay_ = ePay_;
        result.createTimestamp_ = createTimestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.al.cc.java.p3.FeedBackSchema.Feedback) {
          return mergeFrom((com.al.cc.java.p3.FeedBackSchema.Feedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.al.cc.java.p3.FeedBackSchema.Feedback other) {
        if (other == com.al.cc.java.p3.FeedBackSchema.Feedback.getDefaultInstance()) return this;
        if (other.getLifeCycleId() != 0L) {
          setLifeCycleId(other.getLifeCycleId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getGcId().isEmpty()) {
          gcId_ = other.gcId_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.parkingLotType_ != 0) {
          setParkingLotTypeValue(other.getParkingLotTypeValue());
        }
        if (other.getEPay() != false) {
          setEPay(other.getEPay());
        }
        if (other.getCreateTimestamp() != 0L) {
          setCreateTimestamp(other.getCreateTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.al.cc.java.p3.FeedBackSchema.Feedback parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.al.cc.java.p3.FeedBackSchema.Feedback) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long lifeCycleId_ ;
      /**
       * <code>int64 life_cycle_id = 1;</code>
       * @return The lifeCycleId.
       */
      @java.lang.Override
      public long getLifeCycleId() {
        return lifeCycleId_;
      }
      /**
       * <code>int64 life_cycle_id = 1;</code>
       * @param value The lifeCycleId to set.
       * @return This builder for chaining.
       */
      public Builder setLifeCycleId(long value) {
        
        lifeCycleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 life_cycle_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLifeCycleId() {
        
        lifeCycleId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gcId_ = "";
      /**
       * <code>string gc_id = 3;</code>
       * @return The gcId.
       */
      public java.lang.String getGcId() {
        java.lang.Object ref = gcId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gcId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gc_id = 3;</code>
       * @return The bytes for gcId.
       */
      public com.google.protobuf.ByteString
          getGcIdBytes() {
        java.lang.Object ref = gcId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gcId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gc_id = 3;</code>
       * @param value The gcId to set.
       * @return This builder for chaining.
       */
      public Builder setGcId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gc_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGcId() {
        
        gcId_ = getDefaultInstance().getGcId();
        onChanged();
        return this;
      }
      /**
       * <code>string gc_id = 3;</code>
       * @param value The bytes for gcId to set.
       * @return This builder for chaining.
       */
      public Builder setGcIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gcId_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.p3_v1.Gender gender = 4;</code>
       * @return The enum numeric value on the wire for gender.
       */
      @java.lang.Override public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.p3_v1.Gender gender = 4;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.p3_v1.Gender gender = 4;</code>
       * @return The gender.
       */
      @java.lang.Override
      public com.al.cc.java.p3.FeedBackSchema.Gender getGender() {
        @SuppressWarnings("deprecation")
        com.al.cc.java.p3.FeedBackSchema.Gender result = com.al.cc.java.p3.FeedBackSchema.Gender.valueOf(gender_);
        return result == null ? com.al.cc.java.p3.FeedBackSchema.Gender.UNRECOGNIZED : result;
      }
      /**
       * <code>.p3_v1.Gender gender = 4;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(com.al.cc.java.p3.FeedBackSchema.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.p3_v1.Gender gender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 5;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int parkingLotType_ = 0;
      /**
       * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
       * @return The enum numeric value on the wire for parkingLotType.
       */
      @java.lang.Override public int getParkingLotTypeValue() {
        return parkingLotType_;
      }
      /**
       * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
       * @param value The enum numeric value on the wire for parkingLotType to set.
       * @return This builder for chaining.
       */
      public Builder setParkingLotTypeValue(int value) {
        
        parkingLotType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
       * @return The parkingLotType.
       */
      @java.lang.Override
      public com.al.cc.java.p3.FeedBackSchema.ParkingLotType getParkingLotType() {
        @SuppressWarnings("deprecation")
        com.al.cc.java.p3.FeedBackSchema.ParkingLotType result = com.al.cc.java.p3.FeedBackSchema.ParkingLotType.valueOf(parkingLotType_);
        return result == null ? com.al.cc.java.p3.FeedBackSchema.ParkingLotType.UNRECOGNIZED : result;
      }
      /**
       * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
       * @param value The parkingLotType to set.
       * @return This builder for chaining.
       */
      public Builder setParkingLotType(com.al.cc.java.p3.FeedBackSchema.ParkingLotType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        parkingLotType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.p3_v1.ParkingLotType parkingLotType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearParkingLotType() {
        
        parkingLotType_ = 0;
        onChanged();
        return this;
      }

      private boolean ePay_ ;
      /**
       * <code>bool ePay = 7;</code>
       * @return The ePay.
       */
      @java.lang.Override
      public boolean getEPay() {
        return ePay_;
      }
      /**
       * <code>bool ePay = 7;</code>
       * @param value The ePay to set.
       * @return This builder for chaining.
       */
      public Builder setEPay(boolean value) {
        
        ePay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool ePay = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEPay() {
        
        ePay_ = false;
        onChanged();
        return this;
      }

      private long createTimestamp_ ;
      /**
       * <code>int64 create_timestamp = 8;</code>
       * @return The createTimestamp.
       */
      @java.lang.Override
      public long getCreateTimestamp() {
        return createTimestamp_;
      }
      /**
       * <code>int64 create_timestamp = 8;</code>
       * @param value The createTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTimestamp(long value) {
        
        createTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 create_timestamp = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTimestamp() {
        
        createTimestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:p3_v1.Feedback)
    }

    // @@protoc_insertion_point(class_scope:p3_v1.Feedback)
    private static final com.al.cc.java.p3.FeedBackSchema.Feedback DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.al.cc.java.p3.FeedBackSchema.Feedback();
    }

    public static com.al.cc.java.p3.FeedBackSchema.Feedback getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Feedback>
        PARSER = new com.google.protobuf.AbstractParser<Feedback>() {
      @java.lang.Override
      public Feedback parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feedback(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Feedback> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Feedback> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.al.cc.java.p3.FeedBackSchema.Feedback getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p3_v1_Feedback_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p3_v1_Feedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024p3/v1/Feedback.proto\022\005p3_v1\"\300\001\n\010Feedba" +
      "ck\022\025\n\rlife_cycle_id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022" +
      "\r\n\005gc_id\030\003 \001(\t\022\035\n\006gender\030\004 \001(\0162\r.p3_v1.G" +
      "ender\022\n\n\002id\030\005 \001(\t\022-\n\016parkingLotType\030\006 \001(" +
      "\0162\025.p3_v1.ParkingLotType\022\014\n\004ePay\030\007 \001(\010\022\030" +
      "\n\020create_timestamp\030\010 \001(\003*.\n\016ParkingLotTy" +
      "pe\022\017\n\013UNDERGROUND\020\000\022\013\n\007OUTSIDE\020\001*\036\n\006Gend" +
      "er\022\n\n\006FEMALE\020\000\022\010\n\004MALE\020\001B#\n\021com.al.cc.ja" +
      "va.p3B\016FeedBackSchemab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_p3_v1_Feedback_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p3_v1_Feedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p3_v1_Feedback_descriptor,
        new java.lang.String[] { "LifeCycleId", "Name", "GcId", "Gender", "Id", "ParkingLotType", "EPay", "CreateTimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
